language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '8.0'
  - '8.1'

before_script:
  - composer install

script: vendor/phpunit/phpunit/phpunit tests/ --whitelist src/ --coverage-clover build/coverage/xml

after_script:
  - php vendor/bin/codacycoverage clover build/coverage/xml

os: linux